algo = input('digite algo: ')
print('o que voce escreveu só tem numero ?')
print(algo.isnumeric())
print('o que voce escreveu só tem letra ?')
print(algo.isalpha())
print('o que voce escreveu tem letra ou numero ?')
print(algo.isalnum())
print('o que voce escreveu é só espaço ?')
print(algo.isspace())
